[server]
headless = true
port = 8501
runOnSave = true

[theme]
base = "dark"
primaryColor = "#E10600"
backgroundColor = "#0B0D12"
secondaryBackgroundColor = "#161922"
textColor = "#FFFFFF"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
