[server]
headless = true
port = 8501

[theme]
base = "dark"
primaryColor = "#E10600"
backgroundColor = "#0B0D12"
secondaryBackgroundColor = "#161922"
textColor = "#FFFFFF"

[runner]
fastReruns = true
